### ISSUE TITLE
addRosterItem does not add the jid

### ISSUE THREAD

**Issue by ol88** [vukoye/xmpp_dart#10]
Seems to be an issue in the `addRosterItem` method in RosterManager.dart:

`itemElement.addChild(itemElement);` should be `queryElement.addChild(itemElement);`

Also itemElement should get a name otherwise the name will be "null"

`itemElement.name = "item";`

```
Future<IqStanzaResult> addRosterItem(Buddy rosterItem) {
...
    XmppElement queryElement = XmppElement();
    queryElement.name = 'query';
    queryElement.addAttribute(XmppAttribute('xmlns', 'jabber:iq:roster'));
    iqStanza.addChild(queryElement);
    XmppElement itemElement = XmppElement();
    itemElement.name = "item"; //give a name to itemElement so it is not null.
    itemElement.addAttribute(XmppAttribute('jid', rosterItem.jid.userAtDomain));
    if (rosterItem.name != null) {
      itemElement.addAttribute(XmppAttribute('name', rosterItem.name));
    }
    queryElement.addChild(itemElement); //changed from itemElement.add to queryElement.add
    _myUnrespondedIqStanzas[iqStanza.id] = Tuple2(iqStanza, completer);
...
  }
```
Seems to be working once the above changes are made.

Also seems to be applicable to `removeRosterItem` but I haven't used that one yet.

**Comment by jubalh** [comment]
Did you send a PR?

**Comment by ol88** [comment]
Hi

Sorry no, kind of a newbie with git/GitHub and programming in general so just posted a comment/issue. Not sure what the correct workflow to follow.

But happy to help if I can.

Regards,
Olivier Latorre
Baltec IES
+61 410 649 180

________________________________

**Comment by vukoye** [comment]
You are right Oliver,

I applied the fix.

Thanks for noticing.
