### ISSUE TITLE
XEP-0357: Push Notifications

### ISSUE THREAD

**Issue by opensourcegps** [vukoye/xmpp_dart#11]
How to send message that looks like this:

```
<iq type='set' id='some_random_id'>
  <enable xmlns='urn:xmpp:push:0' jid='hfhdemo.xyz' node='A14CD712-C862-4651-8F3F-24F281DBC6E4'>
    <x xmlns='jabber:x:data' type='submit'>
      <field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field>
      <field var='secret'><value>691d8009061936b0b0d31b99fd4053809f3efc2cf81327833c575360ed2595ac</value></field>
    </x>
  </enable>
</iq>
```

to register client for push notifications. I have the secret and node from app server, but sendMessage() only sends message with body. Is there any way to create custom messages?

https://xmpp.org/extensions/xep-0357.html#xmpp-architecture

Any help would be appreciated.

**Comment by opensourcegps** [comment]
Fixed by adding:
```
@override
  void sendRawXML(String _xml_raw) {

    _connection.write(_xml_raw);

  }
```
to MessageHandler.dart

**Comment by vukoye** [comment]
It will be good to structure this little bit, for example to add special IQ message for push.
I have plans to integrate support for XEP-0357. Any help is welcomed.
What push server implementation you are using for this?

**Comment by opensourcegps** [comment]
Thanks for looking into it. I'm using prosody as an appserver to process notifications. I'm happy to help. Is there any way to contact you outside of github?

**Comment by vukoye** [comment]
You can contact me on nemanja.vukoje@gmail.com
