### ISSUE TITLE
Use as FluffyChat backend?

### ISSUE THREAD

**Issue by poVoq** [vukoye/xmpp_dart#16]
Since you are planning to use this in an future client: why not look into adding it to Fluffychat (or forking it), as that is a really nice Flutter based Matrix client:
https://gitlab.com/ChristianPauly/fluffychat-flutter

https://christianpauly.gitlab.io/fluffychat-website/

(there is also an older/alternative QML version for Ubuntu Touch, but the Flutter version is probably the way forward).

**Comment by vukoye** [comment]
Thanks for the tip.
Will try to figure out is that feasible. But this client looks promising
