### ISSUE TITLE
do  xmpp_dart support  connect to  xmpp server openfire  now ? 

### ISSUE THREAD

**Issue by Troverun** [vukoye/xmpp_dart#2]
hi, 
@vukoye
thanks  your work,  I try  connect to xmpp  openfire server, bug not suceess. Maybe I  don't know how to let it work,  
My quection is   xmpp_dart support  connect to  xmpp server openfire  now ?  If  support ,    can add an example code ?   
thankss.  
  

my conect  code like  
  //create   connection
  ```
var userAtDomain = "u1@sky/jjg";
  var password = "u1";
  int  port = 5222;
 

  xmpp.Jid jid = xmpp.Jid.fromFullJid(userAtDomain);
  xmpp.XmppAccount account = xmpp.XmppAccount(userAtDomain, jid.local, jid.domain, password, port);
  xmpp.Connection connection = new xmpp.Connection(account);
  connection.open();
```

in ExampleConnectionStateChangedListener   class 

 ```
 @override
  void onConnectionStateChanged(xmpp.XmppConnectionState state) {

    if (state == xmpp.XmppConnectionState.ReceivingFeatures) {
      print("ReceivingFeatures");   // just  get the status  
    }

    if (state == xmpp.XmppConnectionState.Authenticating) {
          print("Authenticating");
    }

    if (state == xmpp.XmppConnectionState.Closed) {
          print("Closed");
    }

```

print  the   string: 
sending:       <stream:stream
  from='u1@sky'
  to='sky'
  version='1.0'
  xml:lang='en'
  xmlns='jabber:client'
  xmlns:stream='http://etherx.jabber.org/streams'>

 in my  spark  , login string is  

<stream:stream xmlns='jabber:client' to='sky' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' from='u1@sky' xml:lang='en'>
<starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'></starttls>
<stream:stream xmlns='jabber:client' to='sky' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' from='u1@sky' xml:lang='en'>
<auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='SCRAM-SHA-1'>biwsbj11MyxyPSNDU096ckl8cmRuNDBUJnBIW1FycXsubFhPamY1T1Jz</auth>

**Comment by Troverun** [comment]
my conect  code like  
  //create   connection
  var userAtDomain = "u1@sky/jjg";
  var password = "u1";
  int  port = 5222;
 

  xmpp.Jid jid = xmpp.Jid.fromFullJid(userAtDomain);
  xmpp.XmppAccount account = xmpp.XmppAccount(userAtDomain, jid.local, jid.domain, password, port);
  xmpp.Connection connection = new xmpp.Connection(account);
  connection.open();



in ExampleConnectionStateChangedListener   class 

  @override
  void onConnectionStateChanged(xmpp.XmppConnectionState state) {

    if (state == xmpp.XmppConnectionState.ReceivingFeatures) {
      print("ReceivingFeatures");   // just  get the status  
    }

    if (state == xmpp.XmppConnectionState.Authenticating) {
          print("Authenticating");
    }

    if (state == xmpp.XmppConnectionState.Closed) {
          print("Closed");
    }

**Comment by HeartDawnWY** [comment]
hi,
this question can you solve?
