### ISSUE TITLE
How to setup priority and resources

### ISSUE THREAD

**Issue by JiaiHolon** [vukoye/xmpp_dart#20]
I tried to set up resources as follow lines, however it did not work:
```
var userAtDomain = '$xmppId@$xmppDomain/Android';
    xmpp.Jid jid = xmpp.Jid.fromFullJid(userAtDomain);
    print("JID resources:" + jid.resource);
    xmpp.XmppAccountSettings account = xmpp.XmppAccountSettings(
        userAtDomain, jid.local, jid.domain, password, 5222);
    account.resource = "Android";
```
And I did not find any methods to setup presence's priority,  do you have any ideas about it?

**Comment by vukoye** [comment]
Feature was not implemented correctly, fixed with latest pr. 
Custom resource can be set with
xmpp.XmppAccountSettings account = xmpp.XmppAccountSettings( userAtDomain, jid.local, jid.domain, password, 5222, resource: "resource");
