### ISSUE TITLE
Bug report: Stream Management doesn't work after reconnect.

### ISSUE THREAD

**Issue by TatankaConCube** [vukoye/xmpp_dart#28]
**Version:** 0.2.5

**Did it work before:** No, we had same issue on 0.2.3
 
**Steps to reproduce:**
1. Connect to the chat:
```dart
String userJid = ""; // full user jid
xmpp.XmppAccountSettings accountSettings = xmpp.XmppAccountSettings.fromJid(userJid, password);
xmpp.Connection _connection = xmpp.Connection.getInstance(accountSettings);
_connection.connect();
```
2. Close chant connection:
```dart
_connection.close();
```
3. Connect again:
```dart
_connection.connect();
```

**Actual result:**
Request on enabling Stream management doesn't send.
Stream management `ackRequest`s doesn't send to the server.

**Expected result:**
Request on enabling Stream management sends like after first login.
Stream management `ackRequest`s send to the server every 5 second like after first login.

**Additional info:**
Looks like issue related with `StreamManagementModule` and `ConnectionNegotatiorManager` which uses singleton of `StreamManagementModule` and during second login it doesn't initialise, because already has state `NegotiatorState.DONE`.

**Comment by vukoye** [comment]
Can you please check this issue with latest commit?
 I fixed few additional bugs I found.

**Comment by TatankaConCube** [comment]
In the current 'master' branch it is working, thank you for your work. Closing.
