### ISSUE TITLE
Why failed host look up?

### ISSUE THREAD

**Issue by Sean858** [vukoye/xmpp_dart#3]
Hi,
Thanks for your work, it is impressive, but may I ask why below error happens, for my think, I think it is because of the server problem, because I have my own server ip, but how to change.

Type user@domain:
demo@shrs-tr2

Unhandled exception:
SocketException: Failed host lookup: 'shrs-tr2' (OS Error: nodename nor servname provided, or not known, errno = 8)
#0      _NativeSocket.lookup.<anonymous closure> (dart:io-patch/socket_patch.dart:386:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

**Comment by vukoye** [comment]
Can you please retest this, as it's maybe fixed with latest commit
