### ISSUE TITLE
XML dependency version is too low

### ISSUE THREAD

**Issue by Max-Might** [vukoye/xmpp_dart#33]
This project currently depends on `xml: '>=3.2.5 <4.0.0'`.

This is a problem in projects which directly or indirectly depend on xml `4.x.x`.

**Comment by mrhangz** [comment]
I have the same problem. The library is not compatible with other libraries that use `xml: ^4.2.0`
I found that in 0.2.1 it used `xml: ^4.1.0` but then changed to `>=3.2.5 <4.0.0`. Not sure why

**Comment by vukoye** [comment]
xml library updated.
