### ISSUE TITLE
App is getting hanged up when calling connection.connect();

### ISSUE THREAD

**Issue by mrgulshanyadav** [vukoye/xmpp_dart#41]
The app is getting hanged up when creating a new connection. I think it is doing a heavy job in the main thread. We must create a new thread and do processing there.

The issue is only coming in physical devices and not in the emulator.

`
var connection = xmpp.Connection(account);
connection.connect();
`

**Comment by ahmedmehanna** [comment]
The same issue with me, especially in debug mode.

**Comment by vavadiyahiren** [comment]
@mrgulshanyadav you need to make the connection in background thread yourself , Lib is not expected to create a new thread.
