### ISSUE TITLE
Can you add createdDate to MessageStanza

### ISSUE THREAD

**Issue by ahmedmehanna** [vukoye/xmpp_dart#42]
The offline messages are received without a created date(sent date)
So I need to know the created date of received messages to display them in order

Many thanks for your support of this helpful package.

**Comment by marzoukali** [comment]
Yes please .. I have the same issue too

**Comment by vukoye** [comment]
Hi guys. If message is received immediately than received date is created date.
It would be bad practice to relay on sender's clock.
If receiver is offline XEP-0203: Delayed Delivery is implemented.
