### ISSUE TITLE
Connection while App is closed

### ISSUE THREAD

**Issue by xiki808** [vukoye/xmpp_dart#66]
Hi! Is there a way to keep the connection in the background, even when the app is closed? I'm looking for a push notification service just like Firebase Cloud Messaging, but that works between my server and devices running on my local network. 

Thank you for any feedback!

**Comment by TatankaConCube** [comment]
It doesn't make sense, because the system (Android, iOS) will kill your app in the background after some time. A better way here will be to send FCM from your server when the message receiver is offline.
