### ISSUE TITLE
Attention some PRs have been merged in another branch

### ISSUE THREAD

**Issue by Neustradamus** [vukoye/xmpp_dart#75]
@vukoye: Attention some PRs have been merged in another branch:
- https://github.com/vukoye/xmpp_dart/tree/null_safety

**Comment by TatankaConCube** [comment]
now we have [development](https://github.com/vukoye/xmpp_dart/tree/development) branch before releasing next stable version

**Comment by Neustradamus** [comment]
@vukoye, @TatankaConCube: The selected branch is alwyas in master.

Can you look?

Thanks in advance.
