### ISSUE TITLE
Connection error after update to 0.4.4-dev.1

### ISSUE THREAD

**Issue by N0Noorz** [vukoye/xmpp_dart#81]
when openning socket, got this response:
`[log] V/[Connection]: full response = <xmpp_stone><?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="192.168.5.110" id="2apj4gjuur" xml:lang="en" version="1.0"></stream:stream>`

but in Connection.handleResponse:
`try {
        xmlResponse = xml.XmlDocument.parse(fullResponse.replaceAll('<?xml version=\'1.0\'?>', '')).firstChild;
      } catch (e) {
        _unparsedXmlResponse += fullResponse.substring(
            0, fullResponse.length - 13); //remove  xmpp_stone end tag
        xmlResponse = xml.XmlElement(xml.XmlName('error'));
      }`

replaceAll Pattern  not match

with server: Openfire 4.6.7 @TatankaConCube

**Comment by TatankaConCube** [comment]
@N0Noorz you are right, I will think about how to make a universal solution

**Comment by TatankaConCube** [comment]
@N0Noorz or or you can prepare a universal regex for removing the initial element from received packages, for now, they are the next variants:
```xml
<?xml version='1.0'?>
<?xml version='1.0' encoding='UTF-8'?>
```

**Comment by TatankaConCube** [comment]
I have prepared the fix and will publish it soon

**Comment by TatankaConCube** [comment]
@N0Noorz try the version [0.4.4-dev.2](https://pub.dev/packages/xmpp_stone/versions/0.4.4-dev.2)

**Comment by N0Noorz** [comment]
> @N0Noorz try the version [0.4.4-dev.2](https://pub.dev/packages/xmpp_stone/versions/0.4.4-dev.2)

thx, may be there is other problem, 
when use [0.4.3-dev.1](https://pub.dev/packages/xmpp_stone/versions/0.4.3-dev.1) is ok.

0.4.4-dev.2 got this log output:
`[log] ---Xmpp Receiving:---
[log] <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/>
I/flutter (11920): Authenticated
[log] ---Xmpp Sending:---
[log] <?xml version='1.0'?><stream:stream xmlns='jabber:client' version='1.0' xmlns:stream='http://etherx.jabber.org/streams' to='192.168.5.110' xml:lang='en'>
[log] D/[Connection]: State: XmppConnectionState.Authenticated
[log] ---Xmpp Receiving:---
[log] <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="192.168.5.110" id="112472zrey" xml:lang="en" version="1.0"><stream:features><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><ver xmlns="urn:xmpp:features:rosterver"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session><sm xmlns='urn:xmpp:sm:2'/><sm xmlns='urn:xmpp:sm:3'/><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://www.igniterealtime.org/projects/openfire/" ver="YclFS4eKP63ICwiAU9AIJ8otw3A="/></stream:features>
[log] D/[Connection]: processInitialStream`

**Comment by TatankaConCube** [comment]
@N0Noorz could you please point me to the issue? I can't see any issues here. Could you provide please the full log but format it, the single-line log is not readable.

**Comment by N0Noorz** [comment]
@TatankaConCube 
sorry for my reply.
the new verison after 0.4.3, can't hanler this receiving:
ConnectionNegotiatorManager not match any negotiator

```
[log] ---Xmpp Receiving:---
[log] <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="192.168.5.110" id="2ypedpcwdp" xml:lang="en" version="1.0"><stream:features><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><ver xmlns="urn:xmpp:features:rosterver"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session><sm xmlns='urn:xmpp:sm:2'/><sm xmlns='urn:xmpp:sm:3'/><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://www.igniterealtime.org/projects/openfire/" ver="YclFS4eKP63ICwiAU9AIJ8otw3A="/></stream:features>
```


my test:
![image](https://user-images.githubusercontent.com/21277899/194456066-1d49f048-e890-4311-87e0-749c5f55b1a4.png)

in my case, rollback to use xmlResponse!.descendants is ok.
https://github.com/vukoye/xmpp_dart/compare/development...N0Noorz:xmpp_dart:developmenthttps://github.com/vukoye/xmpp_dart/compare/development...N0Noorz:xmpp_dart:development

**Comment by TatankaConCube** [comment]
will be back to this issue later on next week

**Comment by TatankaConCube** [comment]
the version [0.4.4-dev.3](https://pub.dev/packages/xmpp_stone/versions/0.4.4-dev.3) was published, please try it and close this ticket if the issue was resolved

**Comment by N0Noorz** [comment]
done.
thx~
