### ISSUE TITLE
[photo] example code xmpp_stone flutter app says user is authenticated but the user is not actually online on the openfire server 

### ISSUE THREAD

**Issue by isaanyoha** [vukoye/xmpp_dart#88]
![Capturess1](https://user-images.githubusercontent.com/4920405/219939006-57f2eb6a-a25f-460e-9424-064cd62157b8.PNG)

example code from the xmpp_stone flutter package app says user is authenticated but the user is not actually online on the openfire server. How do I resolve this please. Thank you!

tried the example code in versions:
* 0.4.4-dev.2
* 0.4.0-dev.1

**Comment by isaanyoha** [comment]
I noticed version 0.3.3 works and shows that the user is online on the openfire server. However, version 0.3.3 depends on old versions of other flutter packages. 

Please can you set versions 0.4.0 and upward to show that the user is online on openfire server. They use new verion packages. Thank you!

**Comment by TatankaConCube** [comment]
the connection is completely established when the state changed to `Ready`

**Comment by isaanyoha** [comment]
You are correct, that is what it should be. But the issue is that on all the preleased verisions of xmpp_stone, when a client  connect() & state is Ready, openfire sever (Openfire 4.7.4 latest version) does not indicate that the connected client is online that is the client is not listed in (Active 'Client Session', see the image below). But when I downgrade xmpp_stone to 0.3.3 and connect(), it shows the client is online on the openfire server. I have tried this also with older versions of Openfire server still same issue. This issue happens on all the preleased verisions of xmpp_stone but disappears downgrading to verison of xmpp_stone 0.3.3. Again, if user is not online, you can't send/recieve MessageChat, only messages like pings

Please kindly check, maybe there could be something somewhere within the pre-released versions. Or maybe I did not add something in the code? But I am using the exact code that you put up as example in the pre-releases. You may test any of them on openfire and you will confirm my observations.

Thanks for the good work man!

<<<image 1>>>
![Capturess2](https://user-images.githubusercontent.com/4920405/220207999-35fa8640-3bfc-4ff9-8cb1-797f2bd7539f.PNG)

<<<image 2>>>
![Capturess3](https://user-images.githubusercontent.com/4920405/220208511-56787c8f-e5e5-4ade-8eef-db7670cb9922.PNG)

(Images from Openfire, when client connect() via xmpp_stone pre-release versions 0.4.4-dev.2 and others pre-releases)

**Comment by TatankaConCube** [comment]
the version [0.4.4-dev.3](https://pub.dev/packages/xmpp_stone/versions/0.4.4-dev.3) was published, please try it and close this ticket if the issue was resolved

**Comment by isaanyoha** [comment]
Ok, I will try it

**Comment by isaanyoha** [comment]
Ok, I will try it. Thanks for response

**Comment by isaanyoha** [comment]
Yeahhh! It is fixed now. Thanks!
